project_id = "hapzzpwywnahovmddlej"

[functions.invite-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.register-user]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.parse-knowledge-file]
verify_jwt = false

[functions.nanda-chat]
verify_jwt = false